<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-07-05 at 15:37:49.
 */
class ModeratePageManagerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ModeratePageManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ModeratePageManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ModeratePageManager::getTheUpdatedPagesWithLimit
     */
    public function testGetTheUpdatedPagesWithLimit()
    {
        $data = $this->object->getTheUpdatedPagesByUserIdWithLimit(0, 10);

	    $this->assertTrue(is_array($data));
    }

	public function testGetTheUpdatedPagesByModeratePageSearchParams()
	{
		$params = new ModeratePageSearchParams();
		$params->moderate_status_id = ModerateStatusModel::MODERATE;
		$params->offset = 0;
		$params->limit = 10;
		$params->clinic_name = 'Остион';

		$data = $this->object->getTheUpdatedPagesByModeratePageSearchParams($params);
		$this->assertTrue(is_array($data));
	}
}
