<?php
    /**
     * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-17 at 16:53:56.
     */
    class RegisterTest extends PHPUnit_Framework_TestCase
    {

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {

        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {

        }

        /**
         * @covers Register::add
         */
        public function testAdd()
        {
            Register::add('test', 1);
            $this->assertEquals(Register::get('test'), 1);
        }


        /**
         * @covers Register::set
         */
        public function testSet()
        {
            Register::add('test', 1);

            Register::set('test', 2);
            $this->assertEquals(2, Register::get('test'));
        }

        /**
         * @covers Register::remove
         * @expectedException Exception
         */
        public function testRemove()
        {
            Register::add('remove', 2);
            Register::remove('remove');

            Register::get('remove');
        }

        /**
         * @expectedException Exception
         */
        public function testGetUndefinedEntry()
        {
            Register::get('not_exists');
        }
    }
