# docker-compose.yml
version: '3.8'

services:
  php:
    container_name: vet_php
    build: .
    # или используйте image: если уже собрали
    volumes:
      - ./:/var/www
    networks:
      - app-network
  nginx:
    container_name: vet_nginx
    image: docker.io/nginx:alpine
    ports:
      - "8180:80"  # Публикуем порт наружу
    volumes:
      - ./:/var/www  # Общий код
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
  elastic: 
    container_name: vet_elastic 
    image:  docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
       - xpack.security.enabled=false
    ports: 
       - "9400:9200"
       - "9500:9300"
    volumes: 
      - ./docker/elastic/plugins:/usr/share/elasticsearch/plugins
      - ./docker/elastic/data:/usr/share/elasticsearch/data 
    networks:
      - app-network
  memcached:
    container_name: vet_memcached
    image: docker.io/memcached:alpine
    ports:
      - "11212:11211"
    networks:
      - app-network
  mysql:
    container_name: vet_mysql
    image: docker.io/mysql:5.5  # MySQL 5.7 - самая стабильная с PHP 5.6
    ports:
      - "3307:3306"  # Опционально, если нужен доступ с хоста
    environment:
      - MYSQL_ROOT_PASSWORD=dfghmt563
      - MYSQL_DATABASE=lookvetbook
      - MYSQL_USER=look_vet  # Опционально
      - MYSQL_PASSWORD=dfghmt563  # Опционально
    volumes:
      - ./docker/mysql/:/var/lib/mysql  # Сохраняем данные БД
    networks:
      - app-network
    command: 
      - --bind-address=0.0.0.0  # Явно слушаем на всех интерфейсах
networks:
  app-network:
    driver: bridge
