<?php if (debug): ?>
    <script type="text/javascript" src="/media/js/library/registration_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/city.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/login_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/confirm_email.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/password_recovery.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/set_new_password.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/new_email.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_about.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_about_vk_account.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_about_fb_account.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_about_mailru_account.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_about_ok_account.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_family.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_options.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_trust.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/doctor_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/clinic_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/disease_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/disease_search_results_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/disease_search_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/doctor_search_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/doctor_search_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/clinic_search_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/clinic_search_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/yandex_map.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/add_review_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/doctors_visits_coming.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/notification.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/account_main_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/disease_quick_search_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/clinic_doctor_search_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/map_controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/confirm_phone_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/help_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/help_search_results_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/help_quick_search_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_my_doctor_search_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/favorite_doctors_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/schedule_and_clinics_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/doctor_big_card.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_my_disease.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_my_clinic_search_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/favorite_clinics_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/record_to_the_doctor_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/record_phones_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_reviews.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/visit_remind_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/doctor_small_card.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/set_password_landing_registration.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/landing_registration_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/landing_login_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/city_choice.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/landing_license_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/index_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/doctor_big_card_buttons.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/personal_room_doctors_visits_past.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/example_show_cards_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/footer_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/header.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/analysis_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/call_centre_appeal_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/call_centre_operator_doctor_hints.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/product_search.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/about_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/product_live_search.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/expanded_block.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/orders_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/product_card.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/product_basket.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/spin_controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/product_view_card.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/basket_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/basket_item.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/basket_page_controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/order_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/order_form.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/shipping_cost_algorithm.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/product_count_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/jquery.radio.min.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/equal_elements_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/carousel.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/landing_page.controller.js?<?php echo RELEASE_NUMBER?>"></script>
    <script type="text/javascript" src="/media/js/library/disease_links_block.controller.js?<?php echo RELEASE_NUMBER?>"></script>
<?php else: ?>
    <script type="text/javascript" src="/media/js/js_library.js?<?php echo RELEASE_NUMBER?>"></script>
<?php endif; ?>