var script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js';
document.getElementsByTagName('head')[0].appendChild(script);
script.addEventListener('load', function(){

$(document).ready(function() {
    $('head').append('<link rel="stylesheet" href="style.css" type="text/css" />');

jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(e,a,c,b,d){return jQuery.easing[jQuery.easing.def](e,a,c,b,d)},easeInQuad:function(e,a,c,b,d){return b*(a/=d)*a+c},easeOutQuad:function(e,a,c,b,d){return-b*(a/=d)*(a-2)+c},easeInOutQuad:function(e,a,c,b,d){return 1>(a/=d/2)?b/2*a*a+c:-b/2*(--a*(a-2)-1)+c},easeInCubic:function(e,a,c,b,d){return b*(a/=d)*a*a+c},easeOutCubic:function(e,a,c,b,d){return b*((a=a/d-1)*a*a+1)+c},easeInOutCubic:function(e,a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a+c:
b/2*((a-=2)*a*a+2)+c},easeInQuart:function(e,a,c,b,d){return b*(a/=d)*a*a*a+c},easeOutQuart:function(e,a,c,b,d){return-b*((a=a/d-1)*a*a*a-1)+c},easeInOutQuart:function(e,a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a*a+c:-b/2*((a-=2)*a*a*a-2)+c},easeInQuint:function(e,a,c,b,d){return b*(a/=d)*a*a*a*a+c},easeOutQuint:function(e,a,c,b,d){return b*((a=a/d-1)*a*a*a*a+1)+c},easeInOutQuint:function(e,a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a*a*a+c:b/2*((a-=2)*a*a*a*a+2)+c},easeInSine:function(e,a,c,b,d){return-b*Math.cos(a/
d*(Math.PI/2))+b+c},easeOutSine:function(e,a,c,b,d){return b*Math.sin(a/d*(Math.PI/2))+c},easeInOutSine:function(e,a,c,b,d){return-b/2*(Math.cos(Math.PI*a/d)-1)+c},easeInExpo:function(e,a,c,b,d){return 0==a?c:b*Math.pow(2,10*(a/d-1))+c},easeOutExpo:function(e,a,c,b,d){return a==d?c+b:b*(-Math.pow(2,-10*a/d)+1)+c},easeInOutExpo:function(e,a,c,b,d){return 0==a?c:a==d?c+b:1>(a/=d/2)?b/2*Math.pow(2,10*(a-1))+c:b/2*(-Math.pow(2,-10*--a)+2)+c},easeInCirc:function(e,a,c,b,d){return-b*(Math.sqrt(1-(a/=d)*
a)-1)+c},easeOutCirc:function(e,a,c,b,d){return b*Math.sqrt(1-(a=a/d-1)*a)+c},easeInOutCirc:function(e,a,c,b,d){return 1>(a/=d/2)?-b/2*(Math.sqrt(1-a*a)-1)+c:b/2*(Math.sqrt(1-(a-=2)*a)+1)+c},easeInElastic:function(e,a,c,b,d){e=1.70158;var f=0,g=b;if(0==a)return c;if(1==(a/=d))return c+b;f||(f=0.3*d);g<Math.abs(b)?(g=b,e=f/4):e=f/(2*Math.PI)*Math.asin(b/g);return-(g*Math.pow(2,10*(a-=1))*Math.sin(2*(a*d-e)*Math.PI/f))+c},easeOutElastic:function(e,a,c,b,d){e=1.70158;var f=0,g=b;if(0==a)return c;if(1==
(a/=d))return c+b;f||(f=0.3*d);g<Math.abs(b)?(g=b,e=f/4):e=f/(2*Math.PI)*Math.asin(b/g);return g*Math.pow(2,-10*a)*Math.sin(2*(a*d-e)*Math.PI/f)+b+c},easeInOutElastic:function(e,a,c,b,d){e=1.70158;var f=0,g=b;if(0==a)return c;if(2==(a/=d/2))return c+b;f||(f=0.3*d*1.5);g<Math.abs(b)?(g=b,e=f/4):e=f/(2*Math.PI)*Math.asin(b/g);return 1>a?-0.5*g*Math.pow(2,10*(a-=1))*Math.sin(2*(a*d-e)*Math.PI/f)+c:g*Math.pow(2,-10*(a-=1))*Math.sin(2*(a*d-e)*Math.PI/f)*0.5+b+c},easeInBack:function(e,a,c,b,d,f){void 0==
f&&(f=1.70158);return b*(a/=d)*a*((f+1)*a-f)+c},easeOutBack:function(e,a,c,b,d,f){void 0==f&&(f=1.70158);return b*((a=a/d-1)*a*((f+1)*a+f)+1)+c},easeInOutBack:function(e,a,c,b,d,f){void 0==f&&(f=1.70158);return 1>(a/=d/2)?b/2*a*a*(((f*=1.525)+1)*a-f)+c:b/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+c},easeInBounce:function(e,a,c,b,d){return b-jQuery.easing.easeOutBounce(e,d-a,0,b,d)+c},easeOutBounce:function(e,a,c,b,d){return(a/=d)<1/2.75?7.5625*b*a*a+c:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+0.75)+c:a<2.5/2.75?
b*(7.5625*(a-=2.25/2.75)*a+0.9375)+c:b*(7.5625*(a-=2.625/2.75)*a+0.984375)+c},easeInOutBounce:function(e,a,c,b,d){return a<d/2?0.5*jQuery.easing.easeInBounce(e,2*a,0,b,d)+c:0.5*jQuery.easing.easeOutBounce(e,2*a-d,0,b,d)+0.5*b+c}});
(function(f){function c(a){var b=a||window.event,d=[].slice.call(arguments,1),e=0,c=0,g=0;a=f.event.fix(b);a.type="mousewheel";a.wheelDelta&&(e=a.wheelDelta/120);a.detail&&(e=-a.detail/3);g=e;void 0!==b.axis&&b.axis===b.HORIZONTAL_AXIS&&(g=0,c=-1*e);void 0!==b.wheelDeltaY&&(g=b.wheelDeltaY/120);void 0!==b.wheelDeltaX&&(c=-1*b.wheelDeltaX/120);d.unshift(a,e,c,g);return f.event.handle.apply(this,d)}var d=["DOMMouseScroll","mousewheel"];f.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=
d.length;a;)this.addEventListener(d[--a],c,!1);else this.onmousewheel=c},teardown:function(){if(this.removeEventListener)for(var a=d.length;a;)this.removeEventListener(d[--a],c,!1);else this.onmousewheel=null}};f.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);
(function(h){var g={navigate:function(e,d,a,c,f){var b=c.scroll,k=1,g=0;f.expanded&&(b=1,k=3,g=f.idxClicked);if(1===e)a.find("div.ca-item:lt("+b+")").each(function(b){h(this).clone(!0).css("left",(f.totalItems-g+b)*f.itemW*k+"px").appendTo(a)});else{var m=a.children().eq(0);a.find("div.ca-item:gt("+(f.totalItems-1-b)+")").each(function(c){h(this).clone(!0).css("left",-(b-c+g)*f.itemW*k+"px").insertBefore(m)})}a.find("div.ca-item").each(function(d){var a=h(this);a.stop().animate({left:1===e?"-="+f.itemW*
k*b+"px":"+="+f.itemW*k*b+"px"},c.sliderSpeed,c.sliderEasing,function(){(1===e&&a.position().left<-g*f.itemW*k||-1===e&&a.position().left>(f.totalItems-1-g)*f.itemW*k)&&a.remove();f.isAnimating=!1})})},openItem:function(e,d,a,c){c.idxClicked=d.index();c.winpos=g.getWinPos(d.position().left,c);e.find("div.ca-item").not(d).hide();d.find("div.ca-content-wrapper").css("left",c.itemW+"px").stop().animate({width:2*c.itemW+"px",left:c.itemW+"px"},a.itemSpeed,a.itemEasing).end().stop().animate({left:"0px"},
a.itemSpeed,a.itemEasing,function(){c.isAnimating=!1;c.expanded=!0;g.openItems(e,d,a,c)})},openItems:function(e,d,a,c){var f=d.index();e.find("div.ca-item").each(function(b){b=h(this);var a=b.index();a!==f&&(b.css("left",3*-(f-a)*c.itemW+"px").show().find("div.ca-content-wrapper").css({left:c.itemW+"px",width:2*c.itemW+"px"}),g.toggleMore(b,!1))})},toggleMore:function(e,d){d?e.find("a.ca-more").show():e.find("a.ca-more").hide()},closeItems:function(e,d,a,c){var f=d.index();d.find("div.ca-content-wrapper").stop().animate({width:"0px"},
a.itemSpeed,a.itemEasing).end().stop().animate({left:c.itemW*(c.winpos-1)+"px"},a.itemSpeed,a.itemEasing,function(){c.isAnimating=!1;c.expanded=!1});g.toggleMore(d,!0);e.find("div.ca-item").each(function(b){b=h(this);var a=b.index();a!==f&&(b.find("div.ca-content-wrapper").css({width:"0px"}).end().css("left",(c.winpos-1-(f-a))*c.itemW+"px").show(),g.toggleMore(b,!0))})},getWinPos:function(e,d){switch(e){case 0:return 1;case d.itemW:return 2;case 2*d.itemW:return 3}}},l={init:function(e){if(this.length){var d=
{sliderSpeed:500,sliderEasing:"easeOutExpo",itemSpeed:500,itemEasing:"easeOutExpo",scroll:1};return this.each(function(){e&&h.extend(d,e);var a=h(this),c=a.find("div.ca-wrapper"),f=c.children("div.ca-item"),b={};b.itemW=f.width();b.totalItems=f.length;3<b.totalItems&&a.prepend('<div class="ca-nav"><span class="ca-nav-prev"></span><span class="ca-nav-next"></span></div>');1>d.scroll?d.scroll=1:3<d.scroll&&(d.scroll=3);var k=a.find("span.ca-nav-prev"),l=a.find("span.ca-nav-next");c.css("overflow",
"hidden");f.each(function(a){h(this).css({position:"absolute",left:a*b.itemW+"px"})});a.find("a.ca-more").live("click.contentcarousel",function(a){if(b.isAnimating)return!1;b.isAnimating=!0;h(this).hide();a=h(this).closest("div.ca-item");g.openItem(c,a,d,b);return!1});a.find("a.ca-close").live("click.contentcarousel",function(a){if(b.isAnimating)return!1;b.isAnimating=!0;a=h(this).closest("div.ca-item");g.closeItems(c,a,d,b);return!1});k.bind("click.contentcarousel",function(e){if(b.isAnimating)return!1;
b.isAnimating=!0;g.navigate(-1,a,c,d,b)});l.bind("click.contentcarousel",function(e){if(b.isAnimating)return!1;b.isAnimating=!0;g.navigate(1,a,c,d,b)});a.bind("mousewheel.contentcarousel",function(e,f){if(0<f){if(b.isAnimating)return!1;b.isAnimating=!0;g.navigate(-1,a,c,d,b)}else{if(b.isAnimating)return!1;b.isAnimating=!0;g.navigate(1,a,c,d,b)}return!1})})}}};h.fn.contentcarousel=function(e){if(l[e])return l[e].apply(this,Array.prototype.slice.call(arguments,1));if("object"!==typeof e&&e)h.error("Method "+
e+" does not exist on jQuery.contentcarousel");else return l.init.apply(this,arguments)}})(jQuery);

$('.ca-container').width((($('#info-card-widget').width()-60)/204^0) * 204);
setTimeout(function() {
    $('#ca-container').contentcarousel();
    $('#info-card-widget').css('display', 'block');
}, 100);
});}, false);