<?php
	class   ModerateCommentTypeModel
	{
		const CLINIC_FULL_NAME = 100;
		const CLINIC_TYPE = 101;
		const CLINIC_ADDRESS = 102;
		const CLINIC_EMAIL = 103;
		const CLINIC_PHONE = 104;
		const CLINIC_DIRECTOR_FULL_NAME = 105;
		const CLINIC_LICENSE_NUMBER = 106;
		const CLINIC_LICENSE_DATE = 107;
		const CLINIC_LICENSE_IMAGE = 108;
		const CLINIC_LICENSE_SPECIALTIES = 109;
		const CLINIC_DESCRIPTION = 110;
		const CLINIC_FEATURE = 111;
		const CLINIC_NEW_FEATURE = 112;
		const CLINIC_REQISITES_BANK_NAME = 113;
		const CLINIC_REQISITES_BANK_BIK = 114;
		const CLINIC_REQISITES_BANK_INN = 115;
		const CLINIC_REQISITES_BANK_KPP = 116;
		const CLINIC_REQISITES_BANK_RS = 117;
		const CLINIC_REQISITES_BANK_KS = 118;
		const CLINIC_REQISITES_BANK_OGRN = 119;
		const CLINIC_REQISITES_BANK_UR_ADDRESS = 120;
		const CLINIC_REQISITES_BANK_FACT_ADDRESS = 121;
		const CLINIC_SERVICES_IMAGE = 122;
		const CLINIC_SERVICES_SPECIALTIES = 122;

		const DOCTOR_INFORMATION_LAST_NAME = 123;
		const DOCTOR_INFORMATION_FIRST_NAME = 124;
		const DOCTOR_INFORMATION_SECOND_NAME = 125;
		const DOCTOR_INFORMATION_GENDER = 126;
		const DOCTOR_INFORMATION_ABOUT = 127;
		const DOCTOR_SPECIALTIES = 128;

		const DOCTOR_PHOTOS_CARD = 129;
		const DOCTOR_PHOTOS_PHOTOS = 130;

		const CLINIC_AVATAR = 131;
		const CLINIC_PHOTOS = 132;
		const CLINIC_BRIF_INFORMATION_FIO = 133;
		const CLINIC_BRIF_INFORMATION_PHONE = 134;
		const CLINIC_BRIF_INFORMATION_EMAIL = 135;
		const CLINIC_BRIF_INFORMATION_SITE = 138;
		const CLINIC_SITE = 139;


		const CLINIC_CONTRACT_NUMBER = 150;
		const CLINIC_DATE_CONTRACT = 151;
		const CLINIC_LEGAL_ENTITY = 152;

		const CLINIC_RATE = 136;
		const DOCTOR_RATE = 137;

        const DOCTOR_EDUCATION = 153;
        const DOCTOR_COURSE = 154;
        const DOCTOR_CERTIFICATE = 155;
        const DOCTOR_ACADEMIC_TITLE = 156;
	}